#!/bin/bash

touch staging.servers
touch s-pm.servesr
touch s-pm.servers
touch s-ec.servers
touch s-ud.servers
touch s-dd.servers
touch s-gavel.servers
touch q-orapi.servers
touch q-orapi-db.servers
touch q-orapi-app.servers
touch q-orapi-soaapp.servers
touch q-orapi-db-soaapp.servers
touch q-orapi-oem.servers
touch dev.servers
touch d-pm.servesr
touch d-pm.servers
touch d-ec.servers 
touch d-ud.servers 
touch d-dd.servers 
touch d-gavel.servers
touch d-orapi.servers
touch d-orapi-db.servers
touch d-orapi-app.servers
touch d-orapi-soaapp.servers 
touch d-orapi-db-soaapp.servers
touch d-orapi-oem.servers
touch backup.servers
touch b-pm.servesr
touch b-pm.servers
touch b-ec.servers 
touch b-ud.servers 
touch b-dd.servers 
touch b-gavel.servers
touch b-orapi.servers
touch b-orapi-db.servers
touch b-orapi-app.servers
touch b-orapi-soaapp.servers 
touch b-orapi-db-soaapp.servers
touch b-orapi-oem.servers
touch test.servers
touch t-pm.servesr
touch t-pm.servers
touch t-ec.servers 
touch t-ud.servers 
touch t-dd.servers 
touch t-gavel.servers
touch t-orapi.servers
touch t-orapi-db.servers
touch t-orapi-app.servers
touch t-orapi-soaapp.servers 
touch t-orapi-db-soaapp.servers
touch t-orapi-oem.servers
touch training.servers
touch training-pm.servesr
touch demo.servers
touch demo-pm.servers
touch uat.servers
touch u-pm.servesr
touch u-pm.servers
touch u-ec.servers 
touch u-ud.servers
touch u-dd.servers
touch u-gavel.servers
touch u-orapi.servers
touch u-orapi-db.servers
touch u-orapi-app.servers
touch u-orapi-soaapp.servers
touch u-orapi-db-soaapp.servers
touch u-orapi-oem.servers
touch qa.servers
touch q-pm.servesr
touch q-pm.servers
touch q-ec.servers 
touch q-ud.servers
touch q-dd.servers
touch q-gavel.servers
touch misc
